### PR TITLE
add U value and chage decemal value 4 to 7

### PR DESCRIPTION
**Pull request by kaziashik**
change decemal value 4 to 7
add new U value at general move page

### CODE REVIEW

**Comment by ahmdirfnz** [comment]
Screenshot 2023-12-06 at 12 15 47 AM

is there any U input at here?

**Comment by ahmdirfnz** [comment]
Screenshot 2023-12-06 at 12 18 21 AM

I cant see it in general move u edit it

**Comment by kaziashik** [comment]
sorry irfan, it supos to be  Tool-Use page.

**Comment by kaziashik** [comment]
yeah alredy fixed. and send new merge request

https://github.com/ahmdirfnz/Most-Calculator/pull/4

**Comment by ahmdirfnz** [comment]
alright

**Pull request merged**
